# Generated by Django 4.0.4 on 2022-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('price_in_dollars',
                 models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Стоимость в долларах')),
                ('price_in_roubles',
                 models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Стоимость в рублях')),
                ('delivery_time', models.DateField(blank=True, null=True, verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Декларация',
                'verbose_name_plural': 'Декларации',
            },
        ),
    ]
