# Generated by Django 4.0.4 on 2022-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='price_in_roubles',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, unique=True,
                                      verbose_name='Стоимость в рублях'),
        ),
    ]
